### PR TITLE
use getJSON rather than get

### PR DESCRIPTION
**Pull request by paul90**
a fix for #14 

The old `c2.com` site does not respond with `application/JSON` so we don't get the automatic jQuery JSON processing, so we have to use `$.getJSON`.

### CODE REVIEW

**Comment by WardCunningham** [comment]
Seems like a prudent change. But I will revise the perl script at c2.com to have the right headers.

Will try .htaccess as follows:

```
Header add Access-Control-Allow-Origin "*"
Header add Content-Type: application/json
ErrorDocument 404 /findpage.json
```

Hmm. That didn't work. Will consult the web. [post](http://serverfault.com/questions/581760/how-do-i-set-proper-headers-for-json-in-apache)

```
Header add Access-Control-Allow-Origin "*"
AddDefaultCharset utf-8
AddType 'application/json; charset=UTF-8' .json
ErrorDocument 404 /findpage.json
```

Darn. That didn't work either. Suggestions?

**Comment by WardCunningham** [comment]
Oops. I was hacking on the wrong site. That's why that didn't work. I was confusing my first attempt to convert wiki to json, `wiki.c2.com`, with the more successful second attempt, `sfw.c2.com`. 

The looping is avoided. (But why did this mistake cause looping?)

I also see that this conversion cast everything in terms of HTML plugins which we don't yet have in our small-client-wiki. As a read-only application I don't see much harm in implementing such a plugin without running a sanitizer over it. Am I missing something?

**Comment by paul90** [comment]
Think it is just `AddType application/json .json`

**Comment by paul90** [comment]
A HTML plug-in is relatively simple, at it's simplest just use the Markdown plug-in. But, would be better to extend it and sanitize the HTML before passing it to the Markdown plug-in

**Comment by jasonrclark** [comment]
Tested a bit locally (using an extension to force the responses to non-JSON content types) and confirmed this does fix it. Thanks @paul90!

**Pull request merged**
