### PR TITLE
Transpile with babel/webpack and use some es6 features

### PR DESCRIPTION
**Pull request by eknuth**
This change adds a webpack build using [reactpack](https://github.com/olahol/reactpack). The components are broken into es6 modules and a few have been converted into stateless functional components. It also replaces the use of jquery with the new fetch api for retrieving wiki pages.

It might be worth looking at the individual commits. The file layout could be improved and a distinction made between pure ui and components that hold state. Some simple front end routing would also improve the handling of the hash.

### CODE REVIEW

**Comment by WardCunningham** [comment]
I have read each commit and like the direction each one takes. I'd like to hold onto this until Jason is back from the wilderness next week so that we can savor them together.

**Comment by jasonrclark** [comment]
Hey @eknuth, thanks for the code!

When I pulled this down and tried to follow the instructions, I ended up with this failure on `npm start`. Any suggestions for this JS newb?

```
$ npm start

> small-client-wiki@1.0.0 start /Users/jclark/source/small-client-wiki
> reactpack --dev ./src/index.js

/Users/jclark/source/small-client-wiki/node_modules/reactpack/node_modules/extract-text-webpack-plugin/index.js:118
    Object.keys(b).forEach(function(key) {
           ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at mergeOptions (/Users/jclark/source/small-client-wiki/node_modules/reactpack/node_modules/extract-text-webpack-plugin/index.js:118:9)
    at Function.ExtractTextPlugin.extract (/Users/jclark/source/small-client-wiki/node_modules/reactpack/node_modules/extract-text-webpack-plugin/index.js:134:32)
    at module.exports (/Users/jclark/source/small-client-wiki/node_modules/reactpack/config.js:125:33)
    at Object.<anonymous> (/Users/jclark/source/small-client-wiki/node_modules/reactpack/cli.js:60:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 15.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! small-client-wiki@1.0.0 start: `reactpack --dev ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the small-client-wiki@1.0.0 start script 'reactpack --dev ./src/index.js'.
npm ERR! This is most likely a problem with the small-client-wiki package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     reactpack --dev ./src/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls small-client-wiki
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jclark/source/small-client-wiki/npm-debug.log
```

**Comment by eknuth** [comment]
@jasonrclark @WardCunningham, I figured it out. Object.keys did not exist in node v0.12. I tested the pr in versions 4, 5, and 6 with success.

The call to Object.keys happens in the webpack dev server, which is abstracted away in reactpack.  It would probably work in 0.12 with a polyfill, but there really isn't a great place to hook into the dev server.

Maybe we can talk about the big picture for this on Wednesday?

**Comment by jasonrclark** [comment]
Confirmed that locally at home things work 👌  with node 6, as you suspected.

I'll be out on Wednesday, but happy to chat when we can find the time.

**Comment by WardCunningham** [comment]
This pull request will be superseded by #20.  They are similar, but much of the machinery here has been bundled into a single package by the React team which simplifies #20 considerably.

**Pull request closed without merging**
